# Generated by Django 2.2.6 on 2019-10-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('first_name', models.CharField(max_length=60)),
                ('birth_date_place', models.CharField(max_length=60)),
                ('absence_code', models.CharField(max_length=60)),
                ('major', models.CharField(max_length=60)),
                ('high_school', models.CharField(max_length=60)),
                ('line_id', models.CharField(max_length=60)),
                ('instagram', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('interest', models.CharField(max_length=60)),
                ('hope', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
    ]
